name: Docker Image Pull And Test

on:
  workflow_run:
    workflows: ["Docker Image Build And Push"]
    branches: ["main"]
    types:
      - completed

permissions:
  contents: read

jobs:
  pull_test:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/mlops:latest

      - name: Test model
        run: |
          OUTPUT=$(docker run ${{ secrets.DOCKER_USERNAME }}/mlops:latest)
          echo "Score:"
          echo "$OUTPUT"
          if [[ `echo "$OUTPUT 0.20" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
