name: Docker Image Build Push and Pull Test
on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "data/**"
      - "requirements.txt"
      - "README.md"

permissions:
  contents: read

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mlops:latest

  pull_test:
    runs-on: ubuntu-latest
    needs: build_push
    if: success()
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/mlops:latest

      - name: Test model
        run: |
          OUTPUT=$(docker run ${{ secrets.DOCKER_USERNAME }}/mlops:latest)
          echo "Score:"
          echo "$OUTPUT"
          if [[ `echo "$OUTPUT 0.50" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
